In [ ]:
import pandas as pd

In [ ]:
from datasets import load_dataset

In [ ]:
data = load_dataset("roneneldan/TinyStories")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/1.06k [00:00<?, ?B/s]

data/train-00000-of-00004-2d5a1467fff108(…): reconstructing file:   0%|          |  0.00B /  249MB

data/train-00000-of-00004-2d5a1467fff108(…): downloading bytes:           |  0.00B

data/train-00001-of-00004-5852b56a2bd28f(…): reconstructing file:   0%|          |  0.00B /  248MB

data/train-00001-of-00004-5852b56a2bd28f(…): downloading bytes:           |  0.00B

data/train-00002-of-00004-a26307300439e9(…): reconstructing file:   0%|          |  0.00B /  246MB

data/train-00002-of-00004-a26307300439e9(…): downloading bytes:           |  0.00B

data/train-00003-of-00004-d243063613e5a0(…): reconstructing file:   0%|          |  0.00B /  248MB

data/train-00003-of-00004-d243063613e5a0(…): downloading bytes:           |  0.00B

data/validation-00000-of-00001-869c898b5(…): reconstructing file:   0%|          |  0.00B / 9.99MB

data/validation-00000-of-00001-869c898b5(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2119719 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/21990 [00:00<?, ? examples/s]

In [ ]:
print(data)

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 2119719
    })
    validation: Dataset({
        features: ['text'],
        num_rows: 21990
    })
})

In [ ]:
data['train']

Dataset({
    features: ['text'],
    num_rows: 2119719
})

In [ ]:
df = data['train'][0:500]

In [ ]:
df = pd.DataFrame(df)

In [ ]:
df

                                                  text
0    One day, a little girl named Lily found a need...
1    Once upon a time, there was a little car named...
2    One day, a little fish named Fin was swimming ...
3    Once upon a time, in a land full of trees, the...
4    Once upon a time, there was a little girl name...
..                                                 ...
495  One day it was raining. The rain was cold and ...
496  Once upon a time, a little girl lived in a big...
497  Once there was a thin girl named Claire. Clair...
498  Once upon a time there was a boy. He liked to ...
499  Once there was a little puppy named Spot. He l...

[500 rows x 1 columns]

In [ ]:
df = df[:1500]

In [ ]:
df

                                                  text
0    One day, a little girl named Lily found a need...
1    Once upon a time, there was a little car named...
2    One day, a little fish named Fin was swimming ...
3    Once upon a time, in a land full of trees, the...
4    Once upon a time, there was a little girl name...
..                                                 ...
495  One day it was raining. The rain was cold and ...
496  Once upon a time, a little girl lived in a big...
497  Once there was a thin girl named Claire. Clair...
498  Once upon a time there was a boy. He liked to ...
499  Once there was a little puppy named Spot. He l...

[500 rows x 1 columns]

In [ ]:
text = ""
for i in df['text']:
  text = text+i

In [ ]:
text

'One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.\n\nLily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."\n\nTogether, they shared the needle and sewed the button on Lily\'s shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.Once upon a time, there was a little car named Beep. Beep loved to go fast and play in the sun. Beep was a healthy car because he always had good fuel. Good fuel made Beep happy and strong.\n\nOne day, Beep was driving in the park when he saw a big tree. The tree had many leaves that were falling. Beep liked how the leaves fall and wanted to play with them. Beep drove under the tree and watched the leaves fall on him. He laughed and beeped his horn.\n\nBeep played with the falling leaves all day. When it was time to go home, Beep knew he needed more fuel. He went to the fuel place and got more healthy fuel. Now, Beep was ready to go fast and play again the next day. And Beep lived happily ever after.One day, a little fish named Fin was swimming near the shore. He saw a big crab and wanted to be friends. "Hi, I am Fin. Do you want to play?" asked the little fish. The crab looked at Fin and said, "No, I don\'t want to play. I am cold and I don\'t feel fine."\n\nFin felt sad but wanted to help the crab feel better. He swam away and thought of a plan. He remembered that the sun could make things warm. So, Fin swam to the top of the water and called to the sun, "Please, sun, help my new friend feel fine and not freeze!"\n\nThe sun heard Fin\'s call and shone its warm light on the shore. The crab started to feel better and not so cold. He saw Fin and said, "Thank you, little fish, for making me feel fine. I don\'t feel like I will freeze now. Let\'s play together!" And so, Fin and the crab played and became good friends.Once upon a time, in a land full of trees, there was a little cherry tree. The cherry tree was very sad because it did not have any friends. All the other trees were big and strong, but the cherry tree was small and weak. The cherry tree was envious of the big trees.\n\nOne day, the cherry tree felt a tickle in its branches. It was a little spring wind. The wind told the cherry tree not to be sad. The wind said, "You are special because you have sweet cherries that everyone loves." The cherry tree started to feel a little better.\n\nAs time went on, the cherry tree grew more and more cherries. All the animals in the land came to eat the cherries and play under the cherry tree. The cherry tree was happy because it had many friends now. The cherry tree learned that being different can be a good thing. And they all lived happily ever after.Once upon a time, there was a little girl named Lily. Lily liked to pretend she was a popular princess. She lived in a big castle with her best friends, a cat and a dog.\n\nOne day, while playing in the castle, Lily found a big cobweb. The cobweb was in the way of her fun game. She wanted to get rid of it, but she was scared of the spider that lived there.\n\nLily asked her friends, the cat and the dog, to help her. They all worked together to clean the cobweb. The spider was sad, but it found a new home outside. Lily, the cat, and the dog were happy they could play without the cobweb in the way. And they all lived happily ever after.Once upon a time, in a big lake, there was a brown kayak. The brown kayak liked to roll in the water all day long. It was very happy when it could roll and splash in the lake.\n\nOne day, a little boy named Tim came to play with the brown kayak. Tim and the brown kayak rolled in the water together. They laughed and had a lot of fun. The sun was shining, and the water was warm.\n\nAfter a while, it was time for Tim to go home. He said goodbye to the brown kayak and gave it a big hug. The brown kayak was sad to see Tim go, but it knew they would play together again soon. So, the brown kayak kept rolling in the water, waiting for the next fun day with Tim.Once upon a time, in a small town, there was a troubled little girl named Lily. She was always sad because she lost her favorite toy, a triangle. She looked everywhere in her house but could not find it.\n\nOne sunny day, Lily went to the park to play. She saw a big puddle of water and thought her triangle might be there. She put her hand in the water to soak it and looked for her toy. She felt something at the bottom of the puddle.\n\nLily pulled it out and saw that it was her triangle! She was so happy that she found it. From that day on, Lily was never troubled again. She played with her triangle every day and always kept it close to her. And when she saw puddles, she would smile and remember how she found her toy.Once upon a time, in a peaceful town, there lived a little boy named Tim. Tim loved to run and play outside. One day, Tim saw a race in the park. He was excited and wanted to join the race.\n\nTim went to his friend, Sarah, and said, "Let\'s start the race!" Sarah smiled and said, "Yes, let\'s go!" They lined up with the other kids and waited for the race to begin. When they heard the word "Go!", they started running as fast as they could.\n\nTim and Sarah ran with all their speed, laughing and having fun. They could feel the wind in their hair as they raced to the finish line. In the end, Tim won the race and Sarah came in second. They were both so happy and proud of themselves. They celebrated with their friends and had a great day at the park.Once upon a time, there was a clever little dog named Max. Max loved to run and play with his friends in the park. One day, Max was running very fast when he fell and hurt his knee.\n\nMax went to his friend, the wise old owl, and said, "Owl, my knee hurts. What can I do?" The owl thought for a moment and said, "Max, you should test your knee. Try to walk slowly and see if it still hurts."\n\nSo Max tested his knee by walking slowly. At first, it hurt a little, but soon Max felt better. He said, "Thank you, Owl, for your help. Now I can play with my friends again."\n\nMax was so happy that he could play with his friends without pain. He learned that sometimes, it was good to slow down and listen to his body. And Max and his friends played happily in the park ever after.One day, a fast driver named Tim went for a ride in his loud car. He loved to speed down the street and feel the wind in his hair. As he drove, he saw his friend, Sam, standing by the road.\n\n"Hi, Sam!" Tim called out. "Do you want to go for a ride?"\n\n"Yes, please!" Sam said, and he got in the car. They drove around the town, going fast and having fun. The car was very loud, and everyone could hear them coming.\n\nAt last, they stopped at the park to play. They ran and laughed until it was time to go home. Tim and Sam had a great day together, speeding in the loud car and playing in the park.Once upon a time, there was a big car named Dependable. He had a very important job. Dependable would take a family to the park every day. The family had a mom, dad, and a little girl named Lily. They all had a lot of love for each other.\n\nOne day, when they got to the park, they saw a big sign that said, "Fun Race Today!" The family was very excited. They knew that Dependable was very fast and could win the race. So, they decided to join the race.\n\nThe race started, and Dependable went very fast. The other cars tried to catch up, but Dependable was too quick. In the end, Dependable won the race! The family was so happy and proud of their car. They knew that their love for each other and their trust in Dependable made them win the race. And from that day on, they had even more fun at the park, knowing that they had the fastest and most dependable car around.Once upon a time, there was a boy named Tim. He liked to wear a big, dark hat. The hat was his favorite thing to wear. Tim wore the hat everywhere he went.\n\nOne day, Tim found a pencil on the ground. The pencil was small and yellow. Tim liked the pencil a lot. He put the pencil in his hat and took it with him.\n\nTim drew pictures with the pencil. He drew a sun, a tree, and a cat. Tim was very happy with his new pencil. He wore his dark hat and drew pictures every day.One day, a girl named Mia went for a walk. She saw a big, scary house. It had a tall door and small windows. Mia was brave, so she went inside the house.\n\nIn the house, Mia saw a birdcage. Inside the birdcage, there was a little bird. The bird was sad. It wanted to fly and be free. Mia wanted to help the bird.\n\nMia opened the birdcage door. The bird flew out and was happy. It was not scary anymore. Mia and the bird were friends. They played and had fun all day.Once upon a time, in a small house, there lived a little girl named Amy. Amy was very sleepy. She put on her pajamas and went to bed.\n\nIn the middle of the night, Amy heard a soft sound. She opened her eyes and saw a friendly ghost. The ghost said, "Hello, Amy! I am here to help you."\n\nAmy asked the ghost, "Can you help me pick a dream?" The ghost smiled and said, "Of course! Let\'s pick a happy dream for you." Together, they picked a dream about playing in a big park with lots of friends.\n\nAmy said, "Thank you, ghost!" The ghost smiled and said, "You\'re welcome. Now, go back to sleep and enjoy your dream." Amy closed her eyes, feeling happy and safe with her new friend.\n\nAnd so, Amy had a wonderful dream, thanks to the kind ghost. From that night on, the ghost would always visit Amy and help her pick the best dreams, and they became the best of friends.Once upon a time, in a big forest, there was a tiny mushroom. It was all alone. The sun was very harsh, and the mushroom did not like it. It wanted to find a friend to play with and to help it hide from the sun.\n\nOne day, a little bunny came hopping by. The mushroom called out, "Hello, bunny! Will you be my friend?" The bunny looked at the mushroom and smiled. "Sure, I will be your friend. Let\'s play together!" The bunny and the mushroom played all day, and they were very happy.\n\nAs they played, the bunny realized that the mushroom needed help to hide from the harsh sun. So, the bunny dug a hole in the ground and put the mushroom inside. Now, the mushroom was safe and cool. The mushroom and the bunny were the best of friends, and they played in the forest every day.Once upon a time, there was a queen. She was a very nice queen. She had a big, pretty castle. The queen had a lot of work to do every day. But today, she wanted to relax.\n\nThe queen went to the park to relax. She sat on a soft, green grass. The queen saw a bug. The bug was disgusting. The queen did not like the disgusting bug.\n\nThe queen went back to her castle. She was happy to be away from the disgusting bug. Now, the queen could relax in her big, pretty castle. The queen smiled and had a good day.Once upon a time, there was a little white cat named Fluffy. Fluffy loved to play with her best friend, a small boy named Timmy. They played outside in the sun every day. Fluffy liked to chase Timmy, and Timmy liked to run.\n\nOne day, Timmy learned a new word at school. He wanted to teach Fluffy the word too. Timmy said, "Fluffy, the word is \'repeat\'. Can you say \'repeat\'?" Fluffy looked at Timmy and said, "Meow." Timmy laughed and said, "No, Fluffy, say \'repeat\'."\n\nFluffy tried again and said, "Meow-peat." Timmy clapped his hands and said, "Good job, Fluffy! You said the word!" Fluffy was very happy. She liked learning new words with Timmy. From that day on, Fluffy and Timmy played a game where they would teach each other new words. They had lots of fun together, and they lived happily ever after.Once upon a time, there was a big octopus. He lived in the deep blue sea. He had a friend, a reliable fish. They played together every day.\n\nOne day, the octopus and the fish found a big jug. They wanted to pour water on their friends for fun. But they couldn\'t agree on who would pour the water. The octopus said, "I want to pour the water!" The fish said, "No, I want to pour the water!" They were not happy.\n\nThen, the octopus had an idea. He said, "Let\'s both pour the water!" The fish liked the idea. They picked up the big jug together and poured water on all their friends. Everyone laughed and had fun. The octopus and the fish were happy again. They learned to share and play together. And they lived happily ever after.One day, a silly cat named Tom found a hoop in the yard. He wanted to play with it, but it was too big. Tom thought very hard about how to make the hoop smaller.\n\nTom had an idea. He would stretch the hoop to make it smaller. He put his paws on the hoop and pulled as hard as he could. The hoop started to stretch! It got smaller and smaller.\n\nNow, the hoop was just the right size for Tom to play with. He jumped through the hoop and chased it around the yard. Tom had so much fun playing with his new toy. And that is the story of the silly cat and the hoop.Once upon a time, there was a polite crab. The crab lived in the sea. The crab had many friends.\n\nOne day, the crab met a new friend. The new friend did not know how to play. The crab wanted to help the new friend.\n\nThe polite crab showed the new friend how to play. They played all day. They had lots of fun. The new friend was happy. The polite crab was happy too. They were best friends forever.Once, there was a boy named Tim. Tim liked to fish. He had a long pole to catch fish. One day, his friend Sam came to play. Sam saw the pole and asked, "Can you lend me your pole?" Tim said, "Yes, but be careful!"\n\nSam took the pole and went to the river. He tried to catch a fish. He saw a big, yummy fish. He wanted to catch it. He pulled the pole very hard. But the pole broke! Sam felt sad.\n\nSam went back to Tim with the broken pole. He said, "I am sorry, I broke your pole." Tim was very sad. Now, he could not catch yummy fish. They both learned to be more careful with their things.Once upon a time, in a small house, there lived a boy named Tim. Tim was a selfish boy. He did not like to share his things with others. One day, his mom brought home a big bag of vegetables. She wanted to explain to Tim why it was important to share.\n\n"Tim," said Mom, "we need to share these vegetables with our neighbors. It is not good to be selfish." Tim did not want to share the vegetables. He wanted to keep them all for himself. But Mom told him, "If you share, you will make others happy."\n\nTim thought about it and then said, "No, I don\'t want to share." So, he took the vegetables and hid them in his room. The neighbors were sad because they had no food to eat. They knocked on Tim\'s door and asked if he had any food to share. Tim did not want to share, so he said no.\n\nThat night, Tim ate all the vegetables by himself. He felt very full and sick. He wished he had listened to his mom and shared with the neighbors. But now, it was too late. The vegetables were gone, and Tim felt very bad.Once upon a time, there was a girl named Sue. Sue had long hair that would remind her of a rainbow. She would play with her hair all day.\n\nOne day, Sue saw a slow snail in her garden. The snail had a pretty shell. Sue wanted to be friends with the snail. She named the snail Sam.\n\nSue and Sam played together every day. They would race, but Sam was always slow. Sue would laugh and clap her hands. Sue and Sam were very happy.Once upon a time, there was a helpful girl named Lily. She loved to read books and spend time with her friends. One day, she found a new book at school. The book was about a kind bear who helped everyone in the forest.\n\nLily read the book to her friends. They all liked the story. They wanted to be like the kind bear in the book. So, they decided to help others too. They helped their teacher clean the classroom. They also helped their friends when they fell down or needed a friend to play with.\n\nAs they spent more time being helpful, Lily and her friends felt happy. They learned that being kind and helpful to others made them happy too. The moral of the story is to be kind and helpful, just like the kind bear in the book.Once upon a time, there was a little boy named Tim. Tim wanted to build something special for his mom\'s birthday. He thought and thought about what to make. Then, he had an idea! He would build a big present for her.\n\nTim was worried. He didn\'t know if he could build the present all by himself. He asked his dad for help. Together, they found some big boxes, pretty paper, and a big bow. They worked together to make the present look nice.\n\nWhen Tim\'s mom saw the present, she was so happy! She gave Tim a big hug and thanked him for the special gift. Tim felt proud that he could build something so nice for his mom. And he was no longer worried.One day, a big whale was swimming in the deep blue sea. The whale was very mysterious. It had a big smile on its face and liked to play with the little fish.\n\nThe mysterious whale loved to relax in the warm water. It would lay on its back and let the waves rock it like a baby. The little fish would swim around the whale, and they all felt happy and safe.\n\nOne day, the mysterious whale and the little fish found a beautiful place to relax. It was a quiet spot with lots of colorful plants and pretty shells. They all had a fun day, playing and relaxing together in their new secret place.Once upon a time, there was a smelly old tree. By the tree, there was a big hole. In the hole, there was a shiny coin. A boy named Tim saw the coin and wanted it.\n\nTim said to his friend, "I want that coin, but the tree is smelly and rot." His friend said, "Be brave, Tim! You can get the coin." So, Tim went to the smelly tree and tried to get the coin from the hole.\n\nAs Tim got closer to the hole, he saw a little mouse. The mouse said, "I will help you get the coin, but you must help me too." Tim agreed, and they got the coin together. Tim was happy, and the mouse was happy too. And they both learned that even in smelly places, good things can happen.Once upon a time, there was a little boy named Tim. Tim loved going to the park to play. One day, Tim went to the park with his mom and dad. He was very happy.\n\nAt the park, Tim saw a big tree. He wanted to give the tree a hug. So, he hugged the tree and felt good. Tim liked the tree a lot. He played with his ball, ran around, and had a lot of fun.\n\nTim had a successful day at the park. He played and laughed a lot. When it was time to go home, Tim felt tired but happy. He couldn\'t wait to come back to the park again.One sunny day, a pretty boat was on the water. The boat was red and blue. A girl named Lily and her dog, Spot, were on the boat. They liked to play and have fun together.\n\nLily saw a big fish jump out of the water. She said, "Wow, Spot! Did you see that big fish?" Spot barked and wagged his tail. They both laughed and clapped their hands.\n\nLily picked up a hose and started to spray water. She sprayed the water on the boat and on Spot. Spot jumped and barked, trying to catch the water. They played and sprayed water until the sun went down. Then, they went home, happy and wet.Once upon a time, there was a girl named Lily. She had a flute that she loved to play. One day, she met a deaf cat who could not hear her play the flute. Lily wanted to help the cat hear her music.\n\nLily had an idea. She would stretch a big string from her flute to the cat\'s ear. The cat could feel the music through the string. The cat was happy and started to dance.\n\nLily and the deaf cat became best friends. They played and danc

In [ ]:
with open('stories.txt','w') as file:
  file.write(text)

Data Preprocessing

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [ ]:
with open('stories.txt','r') as file:
  data =file.read().lower()

In [ ]:
data

'one day, a little girl named lily found a needle in her room. she knew it was difficult to play with it because it was sharp. lily wanted to share the needle with her mom, so she could sew a button on her shirt.\n\nlily went to her mom and said, "mom, i found this needle. can you share it with me and sew my shirt?" her mom smiled and said, "yes, lily, we can share the needle and fix your shirt."\n\ntogether, they shared the needle and sewed the button on lily\'s shirt. it was not difficult for them because they were sharing and helping each other. after they finished, lily thanked her mom for sharing the needle and fixing her shirt. they both felt happy because they had shared and worked together.once upon a time, there was a little car named beep. beep loved to go fast and play in the sun. beep was a healthy car because he always had good fuel. good fuel made beep happy and strong.\n\none day, beep was driving in the park when he saw a big tree. the tree had many leaves that were falling. beep liked how the leaves fall and wanted to play with them. beep drove under the tree and watched the leaves fall on him. he laughed and beeped his horn.\n\nbeep played with the falling leaves all day. when it was time to go home, beep knew he needed more fuel. he went to the fuel place and got more healthy fuel. now, beep was ready to go fast and play again the next day. and beep lived happily ever after.one day, a little fish named fin was swimming near the shore. he saw a big crab and wanted to be friends. "hi, i am fin. do you want to play?" asked the little fish. the crab looked at fin and said, "no, i don\'t want to play. i am cold and i don\'t feel fine."\n\nfin felt sad but wanted to help the crab feel better. he swam away and thought of a plan. he remembered that the sun could make things warm. so, fin swam to the top of the water and called to the sun, "please, sun, help my new friend feel fine and not freeze!"\n\nthe sun heard fin\'s call and shone its warm light on the shore. the crab started to feel better and not so cold. he saw fin and said, "thank you, little fish, for making me feel fine. i don\'t feel like i will freeze now. let\'s play together!" and so, fin and the crab played and became good friends.once upon a time, in a land full of trees, there was a little cherry tree. the cherry tree was very sad because it did not have any friends. all the other trees were big and strong, but the cherry tree was small and weak. the cherry tree was envious of the big trees.\n\none day, the cherry tree felt a tickle in its branches. it was a little spring wind. the wind told the cherry tree not to be sad. the wind said, "you are special because you have sweet cherries that everyone loves." the cherry tree started to feel a little better.\n\nas time went on, the cherry tree grew more and more cherries. all the animals in the land came to eat the cherries and play under the cherry tree. the cherry tree was happy because it had many friends now. the cherry tree learned that being different can be a good thing. and they all lived happily ever after.once upon a time, there was a little girl named lily. lily liked to pretend she was a popular princess. she lived in a big castle with her best friends, a cat and a dog.\n\none day, while playing in the castle, lily found a big cobweb. the cobweb was in the way of her fun game. she wanted to get rid of it, but she was scared of the spider that lived there.\n\nlily asked her friends, the cat and the dog, to help her. they all worked together to clean the cobweb. the spider was sad, but it found a new home outside. lily, the cat, and the dog were happy they could play without the cobweb in the way. and they all lived happily ever after.once upon a time, in a big lake, there was a brown kayak. the brown kayak liked to roll in the water all day long. it was very happy when it could roll and splash in the lake.\n\none day, a little boy named tim came to play with the brown kayak. tim and the brown kayak rolled in the water together. they laughed and had a lot of fun. the sun was shining, and the water was warm.\n\nafter a while, it was time for tim to go home. he said goodbye to the brown kayak and gave it a big hug. the brown kayak was sad to see tim go, but it knew they would play together again soon. so, the brown kayak kept rolling in the water, waiting for the next fun day with tim.once upon a time, in a small town, there was a troubled little girl named lily. she was always sad because she lost her favorite toy, a triangle. she looked everywhere in her house but could not find it.\n\none sunny day, lily went to the park to play. she saw a big puddle of water and thought her triangle might be there. she put her hand in the water to soak it and looked for her toy. she felt something at the bottom of the puddle.\n\nlily pulled it out and saw that it was her triangle! she was so happy that she found it. from that day on, lily was never troubled again. she played with her triangle every day and always kept it close to her. and when she saw puddles, she would smile and remember how she found her toy.once upon a time, in a peaceful town, there lived a little boy named tim. tim loved to run and play outside. one day, tim saw a race in the park. he was excited and wanted to join the race.\n\ntim went to his friend, sarah, and said, "let\'s start the race!" sarah smiled and said, "yes, let\'s go!" they lined up with the other kids and waited for the race to begin. when they heard the word "go!", they started running as fast as they could.\n\ntim and sarah ran with all their speed, laughing and having fun. they could feel the wind in their hair as they raced to the finish line. in the end, tim won the race and sarah came in second. they were both so happy and proud of themselves. they celebrated with their friends and had a great day at the park.once upon a time, there was a clever little dog named max. max loved to run and play with his friends in the park. one day, max was running very fast when he fell and hurt his knee.\n\nmax went to his friend, the wise old owl, and said, "owl, my knee hurts. what can i do?" the owl thought for a moment and said, "max, you should test your knee. try to walk slowly and see if it still hurts."\n\nso max tested his knee by walking slowly. at first, it hurt a little, but soon max felt better. he said, "thank you, owl, for your help. now i can play with my friends again."\n\nmax was so happy that he could play with his friends without pain. he learned that sometimes, it was good to slow down and listen to his body. and max and his friends played happily in the park ever after.one day, a fast driver named tim went for a ride in his loud car. he loved to speed down the street and feel the wind in his hair. as he drove, he saw his friend, sam, standing by the road.\n\n"hi, sam!" tim called out. "do you want to go for a ride?"\n\n"yes, please!" sam said, and he got in the car. they drove around the town, going fast and having fun. the car was very loud, and everyone could hear them coming.\n\nat last, they stopped at the park to play. they ran and laughed until it was time to go home. tim and sam had a great day together, speeding in the loud car and playing in the park.once upon a time, there was a big car named dependable. he had a very important job. dependable would take a family to the park every day. the family had a mom, dad, and a little girl named lily. they all had a lot of love for each other.\n\none day, when they got to the park, they saw a big sign that said, "fun race today!" the family was very excited. they knew that dependable was very fast and could win the race. so, they decided to join the race.\n\nthe race started, and dependable went very fast. the other cars tried to catch up, but dependable was too quick. in the end, dependable won the race! the family was so happy and proud of their car. they knew that their love for each other and their trust in dependable made them win the race. and from that day on, they had even more fun at the park, knowing that they had the fastest and most dependable car around.once upon a time, there was a boy named tim. he liked to wear a big, dark hat. the hat was his favorite thing to wear. tim wore the hat everywhere he went.\n\none day, tim found a pencil on the ground. the pencil was small and yellow. tim liked the pencil a lot. he put the pencil in his hat and took it with him.\n\ntim drew pictures with the pencil. he drew a sun, a tree, and a cat. tim was very happy with his new pencil. he wore his dark hat and drew pictures every day.one day, a girl named mia went for a walk. she saw a big, scary house. it had a tall door and small windows. mia was brave, so she went inside the house.\n\nin the house, mia saw a birdcage. inside the birdcage, there was a little bird. the bird was sad. it wanted to fly and be free. mia wanted to help the bird.\n\nmia opened the birdcage door. the bird flew out and was happy. it was not scary anymore. mia and the bird were friends. they played and had fun all day.once upon a time, in a small house, there lived a little girl named amy. amy was very sleepy. she put on her pajamas and went to bed.\n\nin the middle of the night, amy heard a soft sound. she opened her eyes and saw a friendly ghost. the ghost said, "hello, amy! i am here to help you."\n\namy asked the ghost, "can you help me pick a dream?" the ghost smiled and said, "of course! let\'s pick a happy dream for you." together, they picked a dream about playing in a big park with lots of friends.\n\namy said, "thank you, ghost!" the ghost smiled and said, "you\'re welcome. now, go back to sleep and enjoy your dream." amy closed her eyes, feeling happy and safe with her new friend.\n\nand so, amy had a wonderful dream, thanks to the kind ghost. from that night on, the ghost would always visit amy and help her pick the best dreams, and they became the best of friends.once upon a time, in a big forest, there was a tiny mushroom. it was all alone. the sun was very harsh, and the mushroom did not like it. it wanted to find a friend to play with and to help it hide from the sun.\n\none day, a little bunny came hopping by. the mushroom called out, "hello, bunny! will you be my friend?" the bunny looked at the mushroom and smiled. "sure, i will be your friend. let\'s play together!" the bunny and the mushroom played all day, and they were very happy.\n\nas they played, the bunny realized that the mushroom needed help to hide from the harsh sun. so, the bunny dug a hole in the ground and put the mushroom inside. now, the mushroom was safe and cool. the mushroom and the bunny were the best of friends, and they played in the forest every day.once upon a time, there was a queen. she was a very nice queen. she had a big, pretty castle. the queen had a lot of work to do every day. but today, she wanted to relax.\n\nthe queen went to the park to relax. she sat on a soft, green grass. the queen saw a bug. the bug was disgusting. the queen did not like the disgusting bug.\n\nthe queen went back to her castle. she was happy to be away from the disgusting bug. now, the queen could relax in her big, pretty castle. the queen smiled and had a good day.once upon a time, there was a little white cat named fluffy. fluffy loved to play with her best friend, a small boy named timmy. they played outside in the sun every day. fluffy liked to chase timmy, and timmy liked to run.\n\none day, timmy learned a new word at school. he wanted to teach fluffy the word too. timmy said, "fluffy, the word is \'repeat\'. can you say \'repeat\'?" fluffy looked at timmy and said, "meow." timmy laughed and said, "no, fluffy, say \'repeat\'."\n\nfluffy tried again and said, "meow-peat." timmy clapped his hands and said, "good job, fluffy! you said the word!" fluffy was very happy. she liked learning new words with timmy. from that day on, fluffy and timmy played a game where they would teach each other new words. they had lots of fun together, and they lived happily ever after.once upon a time, there was a big octopus. he lived in the deep blue sea. he had a friend, a reliable fish. they played together every day.\n\none day, the octopus and the fish found a big jug. they wanted to pour water on their friends for fun. but they couldn\'t agree on who would pour the water. the octopus said, "i want to pour the water!" the fish said, "no, i want to pour the water!" they were not happy.\n\nthen, the octopus had an idea. he said, "let\'s both pour the water!" the fish liked the idea. they picked up the big jug together and poured water on all their friends. everyone laughed and had fun. the octopus and the fish were happy again. they learned to share and play together. and they lived happily ever after.one day, a silly cat named tom found a hoop in the yard. he wanted to play with it, but it was too big. tom thought very hard about how to make the hoop smaller.\n\ntom had an idea. he would stretch the hoop to make it smaller. he put his paws on the hoop and pulled as hard as he could. the hoop started to stretch! it got smaller and smaller.\n\nnow, the hoop was just the right size for tom to play with. he jumped through the hoop and chased it around the yard. tom had so much fun playing with his new toy. and that is the story of the silly cat and the hoop.once upon a time, there was a polite crab. the crab lived in the sea. the crab had many friends.\n\none day, the crab met a new friend. the new friend did not know how to play. the crab wanted to help the new friend.\n\nthe polite crab showed the new friend how to play. they played all day. they had lots of fun. the new friend was happy. the polite crab was happy too. they were best friends forever.once, there was a boy named tim. tim liked to fish. he had a long pole to catch fish. one day, his friend sam came to play. sam saw the pole and asked, "can you lend me your pole?" tim said, "yes, but be careful!"\n\nsam took the pole and went to the river. he tried to catch a fish. he saw a big, yummy fish. he wanted to catch it. he pulled the pole very hard. but the pole broke! sam felt sad.\n\nsam went back to tim with the broken pole. he said, "i am sorry, i broke your pole." tim was very sad. now, he could not catch yummy fish. they both learned to be more careful with their things.once upon a time, in a small house, there lived a boy named tim. tim was a selfish boy. he did not like to share his things with others. one day, his mom brought home a big bag of vegetables. she wanted to explain to tim why it was important to share.\n\n"tim," said mom, "we need to share these vegetables with our neighbors. it is not good to be selfish." tim did not want to share the vegetables. he wanted to keep them all for himself. but mom told him, "if you share, you will make others happy."\n\ntim thought about it and then said, "no, i don\'t want to share." so, he took the vegetables and hid them in his room. the neighbors were sad because they had no food to eat. they knocked on tim\'s door and asked if he had any food to share. tim did not want to share, so he said no.\n\nthat night, tim ate all the vegetables by himself. he felt very full and sick. he wished he had listened to his mom and shared with the neighbors. but now, it was too late. the vegetables were gone, and tim felt very bad.once upon a time, there was a girl named sue. sue had long hair that would remind her of a rainbow. she would play with her hair all day.\n\none day, sue saw a slow snail in her garden. the snail had a pretty shell. sue wanted to be friends with the snail. she named the snail sam.\n\nsue and sam played together every day. they would race, but sam was always slow. sue would laugh and clap her hands. sue and sam were very happy.once upon a time, there was a helpful girl named lily. she loved to read books and spend time with her friends. one day, she found a new book at school. the book was about a kind bear who helped everyone in the forest.\n\nlily read the book to her friends. they all liked the story. they wanted to be like the kind bear in the book. so, they decided to help others too. they helped their teacher clean the classroom. they also helped their friends when they fell down or needed a friend to play with.\n\nas they spent more time being helpful, lily and her friends felt happy. they learned that being kind and helpful to others made them happy too. the moral of the story is to be kind and helpful, just like the kind bear in the book.once upon a time, there was a little boy named tim. tim wanted to build something special for his mom\'s birthday. he thought and thought about what to make. then, he had an idea! he would build a big present for her.\n\ntim was worried. he didn\'t know if he could build the present all by himself. he asked his dad for help. together, they found some big boxes, pretty paper, and a big bow. they worked together to make the present look nice.\n\nwhen tim\'s mom saw the present, she was so happy! she gave tim a big hug and thanked him for the special gift. tim felt proud that he could build something so nice for his mom. and he was no longer worried.one day, a big whale was swimming in the deep blue sea. the whale was very mysterious. it had a big smile on its face and liked to play with the little fish.\n\nthe mysterious whale loved to relax in the warm water. it would lay on its back and let the waves rock it like a baby. the little fish would swim around the whale, and they all felt happy and safe.\n\none day, the mysterious whale and the little fish found a beautiful place to relax. it was a quiet spot with lots of colorful plants and pretty shells. they all had a fun day, playing and relaxing together in their new secret place.once upon a time, there was a smelly old tree. by the tree, there was a big hole. in the hole, there was a shiny coin. a boy named tim saw the coin and wanted it.\n\ntim said to his friend, "i want that coin, but the tree is smelly and rot." his friend said, "be brave, tim! you can get the coin." so, tim went to the smelly tree and tried to get the coin from the hole.\n\nas tim got closer to the hole, he saw a little mouse. the mouse said, "i will help you get the coin, but you must help me too." tim agreed, and they got the coin together. tim was happy, and the mouse was happy too. and they both learned that even in smelly places, good things can happen.once upon a time, there was a little boy named tim. tim loved going to the park to play. one day, tim went to the park with his mom and dad. he was very happy.\n\nat the park, tim saw a big tree. he wanted to give the tree a hug. so, he hugged the tree and felt good. tim liked the tree a lot. he played with his ball, ran around, and had a lot of fun.\n\ntim had a successful day at the park. he played and laughed a lot. when it was time to go home, tim felt tired but happy. he couldn\'t wait to come back to the park again.one sunny day, a pretty boat was on the water. the boat was red and blue. a girl named lily and her dog, spot, were on the boat. they liked to play and have fun together.\n\nlily saw a big fish jump out of the water. she said, "wow, spot! did you see that big fish?" spot barked and wagged his tail. they both laughed and clapped their hands.\n\nlily picked up a hose and started to spray water. she sprayed the water on the boat and on spot. spot jumped and barked, trying to catch the water. they played and sprayed water until the sun went down. then, they went home, happy and wet.once upon a time, there was a girl named lily. she had a flute that she loved to play. one day, she met a deaf cat who could not hear her play the flute. lily wanted to help the cat hear her music.\n\nlily had an idea. she would stretch a big string from her flute to the cat\'s ear. the cat could feel the music through the string. the cat was happy and started to dance.\n\nlily and the deaf cat became best friends. they played and danc

Tokenize the text

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index)+1
total_words

3554

In [ ]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'a': 4,
 'was': 5,
 'he': 6,
 'she': 7,
 'it': 8,
 'her': 9,
 'so': 10,
 'in': 11,
 'said': 12,
 'they': 13,
 'of': 14,
 'his': 15,
 'that': 16,
 'day': 17,
 'had': 18,
 'with': 19,
 'little': 20,
 'there': 21,
 'time': 22,
 'but': 23,
 'one': 24,
 'you': 25,
 'very': 26,
 'girl': 27,
 'on': 28,
 'for': 29,
 'once': 30,
 'happy': 31,
 'were': 32,
 'saw': 33,
 'upon': 34,
 'big': 35,
 'all': 36,
 'up': 37,
 'when': 38,
 'wanted': 39,
 'i': 40,
 'then': 41,
 'smiled': 42,
 'him': 43,
 'went': 44,
 'around': 45,
 'mom': 46,
 'be': 47,
 'at': 48,
 'friends': 49,
 'boy': 50,
 'as': 51,
 'out': 52,
 'would': 53,
 'looked': 54,
 'from': 55,
 'something': 56,
 'go': 57,
 'could': 58,
 'back': 59,
 'asked': 60,
 'started': 61,
 'excited': 62,
 'ran': 63,
 'jack': 64,
 'what': 65,
 'can': 66,
 'play': 67,
 'together': 68,
 'felt': 69,
 'help': 70,
 'too': 71,
 'away': 72,
 'old': 73,
 'home': 74,
 'fun': 75,
 'have': 76,
 'found': 77,
 'who': 78,
 'loved': 79,
 'decided': 80,
 'them': 81,
 'again': 82,
 'special': 83,
 'named': 84,
 'an': 85,
 'their': 86,
 'like': 87,
 'playing': 88,
 'suddenly': 89,
 'made': 90,
 'park': 91,
 'always': 92,
 'got': 93,
 'â€': 94,
 'do': 95,
 'get': 96,
 'tim': 97,
 'never': 98,
 'this': 99,
 'is': 100,
 'take': 101,
 'some': 102,
 'man': 103,
 'every': 104,
 'about': 105,
 'make': 106,
 'put': 107,
 'down': 108,
 'new': 109,
 'friend': 110,
 'everyone': 111,
 'not': 112,
 'how': 113,
 'no': 114,
 'thought': 115,
 'see': 116,
 'john': 117,
 'after': 118,
 'soon': 119,
 'sad': 120,
 'outside': 121,
 'mommy': 122,
 'much': 123,
 'other': 124,
 'we': 125,
 'into': 126,
 'knew': 127,
 'things': 128,
 'bird': 129,
 'took': 130,
 'inside': 131,
 'more': 132,
 'scared': 133,
 'dad': 134,
 'small': 135,
 'came': 136,
 "couldn't": 137,
 'two': 138,
 'tree': 139,
 'garden': 140,
 'just': 141,
 'water': 142,
 'find': 143,
 'if': 144,
 'thanked': 145,
 'called': 146,
 'now': 147,
 'heard': 148,
 "let's": 149,
 'sky': 150,
 'way': 151,
 'kept': 152,
 'lucy': 153,
 'will': 154,
 'look': 155,
 'off': 156,
 'lily': 157,
 'feeling': 158,
 "it's": 159,
 'noticed': 160,
 'even': 161,
 'come': 162,
 'me': 163,
 'my': 164,
 'beautiful': 165,
 'house': 166,
 'until': 167,
 'lots': 168,
 'over': 169,
 'molly': 170,
 'proud': 171,
 'gave': 172,
 'walking': 173,
 "didn't": 174,
 'sun': 175,
 'lived': 176,
 'before': 177,
 'explore': 178,
 'mum': 179,
 'told': 180,
 'best': 181,
 'laughed': 182,
 'want': 183,
 'by': 184,
 'ground': 185,
 'your': 186,
 "don't": 187,
 'tried': 188,
 'jane': 189,
 'bear': 190,
 'quickly': 191,
 'mummy': 192,
 'each': 193,
 'liked': 194,
 'feel': 195,
 'sarah': 196,
 'sam': 197,
 'know': 198,
 'room': 199,
 'because': 200,
 'while': 201,
 'hugged': 202,
 'joe': 203,
 "i'm": 204,
 'rabbit': 205,
 'did': 206,
 'better': 207,
 'its': 208,
 'are': 209,
 'end': 210,
 'sure': 211,
 'why': 212,
 'three': 213,
 'tom': 214,
 'closer': 215,
 'boat': 216,
 'walked': 217,
 'looking': 218,
 'daisy': 219,
 'watched': 220,
 'ever': 221,
 'flew': 222,
 'careful': 223,
 'both': 224,
 'smile': 225,
 'great': 226,
 'seen': 227,
 'good': 228,
 'long': 229,
 'still': 230,
 'yes': 231,
 'stopped': 232,
 'bob': 233,
 'stay': 234,
 'played': 235,
 'animals': 236,
 'eyes': 237,
 'people': 238,
 'goodbye': 239,
 'family': 240,
 'began': 241,
 'finally': 242,
 'next': 243,
 'going': 244,
 'opened': 245,
 'bug': 246,
 'world': 247,
 'puppy': 248,
 'car': 249,
 'place': 250,
 'been': 251,
 'voice': 252,
 'daddy': 253,
 'jimmy': 254,
 'toy': 255,
 'kind': 256,
 'jill': 257,
 'years': 258,
 'ready': 259,
 'here': 260,
 'forest': 261,
 'nice': 262,
 'jumped': 263,
 'box': 264,
 'adventure': 265,
 'brave': 266,
 'hard': 267,
 'carefully': 268,
 'many': 269,
 'mia': 270,
 'nodded': 271,
 'fast': 272,
 'mouse': 273,
 'curious': 274,
 'bit': 275,
 'learned': 276,
 'having': 277,
 'wonderful': 278,
 'idea': 279,
 'replied': 280,
 'magical': 281,
 'became': 282,
 'game': 283,
 'lot': 284,
 'waved': 285,
 'run': 286,
 'running': 287,
 'work': 288,
 'strange': 289,
 'grabbed': 290,
 'bed': 291,
 'picked': 292,
 'face': 293,
 'tired': 294,
 'try': 295,
 'walk': 296,
 'first': 297,
 'grass': 298,
 'right': 299,
 'through': 300,
 'food': 301,
 'pond': 302,
 "that's": 303,
 'share': 304,
 'full': 305,
 'door': 306,
 'safe': 307,
 'wait': 308,
 'show': 309,
 'butterfly': 310,
 'fish': 311,
 'coming': 312,
 'give': 313,
 'filled': 314,
 'surprise': 315,
 'warm': 316,
 'thing': 317,
 'night': 318,
 'keep': 319,
 'himself': 320,
 'sue': 321,
 'flowers': 322,
 'truck': 323,
 'arrived': 324,
 'shouted': 325,
 'parents': 326,
 'noise': 327,
 'enjoyed': 328,
 'strong': 329,
 'different': 330,
 'dog': 331,
 'hug': 332,
 'should': 333,
 'where': 334,
 'red': 335,
 'toys': 336,
 'leaves': 337,
 'being': 338,
 'cat': 339,
 'slowly': 340,
 'need': 341,
 'flower': 342,
 'really': 343,
 'stepped': 344,
 'mary': 345,
 'happily': 346,
 'eat': 347,
 'max': 348,
 'spot': 349,
 'secret': 350,
 'amazing': 351,
 'done': 352,
 'kitty': 353,
 'child': 354,
 'stayed': 355,
 'delicious': 356,
 'surprised': 357,
 'joy': 358,
 'cold': 359,
 'remembered': 360,
 'top': 361,
 'listen': 362,
 'important': 363,
 'yummy': 364,
 'head': 365,
 'continued': 366,
 'ice': 367,
 'lesson': 368,
 'eventually': 369,
 'getting': 370,
 'behind': 371,
 'fox': 372,
 'mother': 373,
 'everything': 374,
 'few': 375,
 'loud': 376,
 'pick': 377,
 'deep': 378,
 'gone': 379,
 'able': 380,
 'use': 381,
 'than': 382,
 'black': 383,
 'someone': 384,
 'hopped': 385,
 'morning': 386,
 'andy': 387,
 'thank': 388,
 'trees': 389,
 'everywhere': 390,
 'hand': 391,
 'catch': 392,
 'story': 393,
 'cry': 394,
 'high': 395,
 'seemed': 396,
 'herself': 397,
 'faster': 398,
 'wind': 399,
 'close': 400,
 'hole': 401,
 'showed': 402,
 'bigger': 403,
 'cream': 404,
 'anything': 405,
 'name': 406,
 'young': 407,
 'amazed': 408,
 'figure': 409,
 'learn': 410,
 'frank': 411,
 'near': 412,
 'most': 413,
 'dark': 414,
 'fly': 415,
 'amy': 416,
 'hello': 417,
 'realized': 418,
 'fluffy': 419,
 'timmy': 420,
 'teacher': 421,
 'also': 422,
 'trying': 423,
 'birds': 424,
 'reached': 425,
 'only': 426,
 'across': 427,
 'towards': 428,
 'move': 429,
 'remember': 430,
 'sorry': 431,
 'bad': 432,
 'longer': 433,
 'shiny': 434,
 'must': 435,
 'touch': 436,
 'used': 437,
 'care': 438,
 'perfect': 439,
 'exploring': 440,
 'glad': 441,
 'meadow': 442,
 'finished': 443,
 'please': 444,
 'owl': 445,
 'moment': 446,
 'bunny': 447,
 'hands': 448,
 'let': 449,
 'lady': 450,
 'dinner': 451,
 'far': 452,
 'woods': 453,
 'children': 454,
 'worked': 455,
 'needed': 456,
 'making': 457,
 'hurt': 458,
 'today': 459,
 'tall': 460,
 'pretty': 461,
 'sat': 462,
 'others': 463,
 'ball': 464,
 'elephant': 465,
 'okay': 466,
 'looks': 467,
 'enough': 468,
 'billy': 469,
 'well': 470,
 'believe': 471,
 'year': 472,
 'us': 473,
 'jenny': 474,
 'emma': 475,
 'am': 476,
 'any': 477,
 'sweet': 478,
 'race': 479,
 'anymore': 480,
 'closed': 481,
 'ate': 482,
 'monster': 483,
 'promised': 484,
 'adventures': 485,
 'pink': 486,
 'tasted': 487,
 'happened': 488,
 'naughty': 489,
 'creature': 490,
 'snow': 491,
 'rest': 492,
 'shirt': 493,
 'soft': 494,
 'blue': 495,
 'agreed': 496,
 'gum': 497,
 'patient': 498,
 'followed': 499,
 'brother': 500,
 'blanket': 501,
 'open': 502,
 'ben': 503,
 'shared': 504,
 'drove': 505,
 'clean': 506,
 'favorite': 507,
 'sleep': 508,
 'visit': 509,
 'green': 510,
 'white': 511,
 'moral': 512,
 'own': 513,
 'side': 514,
 'wrong': 515,
 'bright': 516,
 'teddy': 517,
 'store': 518,
 'same': 519,
 'animal': 520,
 'whenever': 521,
 'mama': 522,
 'pirate': 523,
 'cave': 524,
 'mill': 525,
 'light': 526,
 'sunny': 527,
 'join': 528,
 'fell': 529,
 'love': 530,
 'friendly': 531,
 'ghost': 532,
 'cool': 533,
 'helped': 534,
 'baby': 535,
 'caught': 536,
 'worry': 537,
 'bush': 538,
 "what's": 539,
 'grace': 540,
 'relieved': 541,
 'tell': 542,
 'talk': 543,
 'else': 544,
 "wasn't": 545,
 'leave': 546,
 'magic': 547,
 'lost': 548,
 'kids': 549,
 'hear': 550,
 "you're": 551,
 'alone': 552,
 'school': 553,
 'say': 554,
 'clapped': 555,
 'brought': 556,
 'listened': 557,
 'rock': 558,
 'quiet': 559,
 'pocket': 560,
 'think': 561,
 'life': 562,
 'dress': 563,
 'such': 564,
 'cake': 565,
 'hours': 566,
 'angry': 567,
 'set': 568,
 'which': 569,
 'stop': 570,
 'exciting': 571,
 'party': 572,
 'giant': 573,
 'harbor': 574,
 'lonely': 575,
 'excitement': 576,
 'tommy': 577,
 'might': 578,
 'pulled': 579,
 'yellow': 580,
 'free': 581,
 'hide': 582,
 'yard': 583,
 'river': 584,
 'broken': 585,
 'present': 586,
 'worried': 587,
 'wow': 588,
 'taste': 589,
 'gathered': 590,
 'flying': 591,
 'stories': 592,
 'wondered': 593,
 'oh': 594,
 'shopkeeper': 595,
 'ella': 596,
 'jim': 597,
 'taking': 598,
 'appeared': 599,
 'gentle': 600,
 'mean': 601,
 'bell': 602,
 'air': 603,
 'prince': 604,
 'plant': 605,
 'helicopter': 606,
 'violin': 607,
 'fix': 608,
 'under': 609,
 'lake': 610,
 'shining': 611,
 'town': 612,
 'waited': 613,
 'laughing': 614,
 'ride': 615,
 'dependable': 616,
 'sound': 617,
 'met': 618,
 'wished': 619,
 'bow': 620,
 'wet': 621,
 'dance': 622,
 'elly': 623,
 'path': 624,
 'hill': 625,
 'explained': 626,
 'huge': 627,
 'bite': 628,
 'donâ€™t': 629,
 'nothing': 630,
 'forgot': 631,
 'held': 632,
 'moved': 633,
 'belonged': 634,
 '3': 635,
 'fairy': 636,
 'rachel': 637,
 'spotted': 638,
 'farmer': 639,
 'onto': 640,
 "can't": 641,
 'beetle': 642,
 'heart': 643,
 'furry': 644,
 'grandma': 645,
 'sandy': 646,
 'fight': 647,
 'drink': 648,
 'pig': 649,
 'crab': 650,
 'without': 651,
 'speed': 652,
 'knee': 653,
 'wear': 654,
 'middle': 655,
 'teach': 656,
 'words': 657,
 'reliable': 658,
 'bag': 659,
 'spent': 660,
 'birthday': 661,
 'mysterious': 662,
 'colorful': 663,
 'coin': 664,
 'jump': 665,
 'dry': 666,
 'benny': 667,
 'watch': 668,
 'buy': 669,
 'climb': 670,
 'eating': 671,
 'woman': 672,
 'chest': 673,
 'returned': 674,
 'beach': 675,
 'market': 676,
 'june': 677,
 'frustrated': 678,
 'sally': 679,
 'sunshine': 680,
 'sit': 681,
 'blocks': 682,
 'jet': 683,
 'hi': 684,
 'land': 685,
 'peaceful': 686,
 'word': 687,
 'standing': 688,
 'or': 689,
 'build': 690,
 'music': 691,
 'later': 692,
 'embarrassed': 693,
 'cheered': 694,
 'spoke': 695,
 'orange': 696,
 'grow': 697,
 'bloom': 698,
 'dangerous': 699,
 'watching': 700,
 'balloon': 701,
 'emily': 702,
 'covered': 703,
 'fit': 704,
 'mirror': 705,
 'front': 706,
 'obedient': 707,
 'lit': 708,
 'anyone': 709,
 'another': 710,
 'dropped': 711,
 'ocean': 712,
 'playground': 713,
 'bears': 714,
 'parade': 715,
 'swing': 716,
 'penny': 717,
 'smiling': 718,
 'peter': 719,
 'horse': 720,
 'stranger': 721,
 'squash': 722,
 'subway': 723,
 'helping': 724,
 'beep': 725,
 'shore': 726,
 'cherry': 727,
 'wise': 728,
 'driver': 729,
 'street': 730,
 'job': 731,
 'hat': 732,
 'course': 733,
 'relax': 734,
 'our': 735,
 'late': 736,
 'places': 737,
 'tail': 738,
 'danced': 739,
 'left': 740,
 'wide': 741,
 'meet': 742,
 'money': 743,
 'doing': 744,
 'match': 745,
 'understand': 746,
 'though': 747,
 'frog': 748,
 'matter': 749,
 'rake': 750,
 'interesting': 751,
 'warrior': 752,
 'sailed': 753,
 'forget': 754,
 'along': 755,
 'branch': 756,
 'woke': 757,
 'print': 758,
 'enjoying': 759,
 'shy': 760,
 'â€œi': 761,
 'village': 762,
 'rude': 763,
 'tight': 764,
 'circle': 765,
 'phone': 766,
 'stone': 767,
 'daughter': 768,
 'danny': 769,
 'whole': 770,
 'james': 771,
 'mole': 772,
 'alice': 773,
 'vine': 774,
 'freezer': 775,
 'jacky': 776,
 'rug': 777,
 'jungle': 778,
 'button': 779,
 'plan': 780,
 'castle': 781,
 'brown': 782,
 'bottom': 783,
 'sometimes': 784,
 'slow': 785,
 'sign': 786,
 'dream': 787,
 'enjoy': 788,
 'tiny': 789,
 'hopping': 790,
 'queen': 791,
 'pole': 792,
 'selfish': 793,
 'snail': 794,
 'laugh': 795,
 'paper': 796,
 'swim': 797,
 'piece': 798,
 'escape': 799,
 'hot': 800,
 'maybe': 801,
 'slide': 802,
 'turned': 803,
 'stuck': 804,
 'bring': 805,
 'spread': 806,
 'wings': 807,
 'mountain': 808,
 'unusual': 809,
 'confused': 810,
 'talking': 811,
 'charlie': 812,
 'searching': 813,
 'admire': 814,
 'imagined': 815,
 'pointed': 816,
 'tough': 817,
 'comfortable': 818,
 'brightly': 819,
 'summer': 820,
 'trip': 821,
 'painter': 822,
 'purple': 823,
 'field': 824,
 'backyard': 825,
 'taught': 826,
 'since': 827,
 'nap': 828,
 'explored': 829,
 'passport': 830,
 "won't": 831,
 'moving': 832,
 'minutes': 833,
 'kite': 834,
 'become': 835,
 'feet': 836,
 'generous': 837,
 'times': 838,
 'accept': 839,
 'dancing': 840,
 'ok': 841,
 'cozy': 842,
 'engine': 843,
 'hairy': 844,
 'denise': 845,
 'fridge': 846,
 'counting': 847,
 'isabel': 848,
 'soldiers': 849,
 'wood': 850,
 'hay': 851,
 'model': 852,
 'claire': 853,
 'dove': 854,
 'mae': 855,
 'russel': 856,
 'hook': 857,
 'grandbaby': 858,
 'doctor': 859,
 'rhinoceros': 860,
 'cushion': 861,
 'fall': 862,
 'swimming': 863,
 'line': 864,
 'last': 865,
 'welcome': 866,
 'mushroom': 867,
 'octopus': 868,
 'sea': 869,
 'forever': 870,
 'helpful': 871,
 'deaf': 872,
 'vest': 873,
 'lunch': 874,
 'zigzag': 875,
 'search': 876,
 'pushed': 877,
 'makes': 878,
 'bedroom': 879,
 'pushing': 880,
 'sweetheart': 881,
 'instead': 882,
 'delicate': 883,
 'milk': 884,
 'problem': 885,
 'mind': 886,
 'follow': 887,
 'favourite': 888,
 'brush': 889,
 'caterpillar': 890,
 'disappeared': 891,
 "wouldn't": 892,
 'squirrel': 893,
 'itâ€™s': 894,
 'journey': 895,
 'bucket': 896,
 'â€œletâ€™s': 897,
 'sail': 898,
 'sack': 899,
 'heavy': 900,
 'zip': 901,
 'understood': 902,
 'susie': 903,
 'cheerful': 904,
 'crying': 905,
 'island': 906,
 'nearby': 907,
 'wand': 908,
 'shook': 909,
 'break': 910,
 'paul': 911,
 'asking': 912,
 'dinosaur': 913,
 'everyday': 914,
 'tower': 915,
 'picnic': 916,
 'reminded': 917,
 'playful': 918,
 'circles': 919,
 'turtle': 920,
 'climbed': 921,
 'basket': 922,
 'turkey': 923,
 'kinds': 924,
 'answer': 925,
 'henry': 926,
 'rare': 927,
 'write': 928,
 'football': 929,
 'key': 930,
 'stack': 931,
 'candle': 932,
 'pilot': 933,
 'jog': 934,
 'shapes': 935,
 'witch': 936,
 'leo': 937,
 'pool': 938,
 'jacket': 939,
 'spaghetti': 940,
 'crane': 941,
 'goat': 942,
 'pretend': 943,
 'splash': 944,
 'hair': 945,
 'won': 946,
 'knowing': 947,
 'birdcage': 948,
 'hoop': 949,
 'rainbow': 950,
 'book': 951,
 'happen': 952,
 'rain': 953,
 'float': 954,
 'nervous': 955,
 'ears': 956,
 'empty': 957,
 'messy': 958,
 'binky': 959,
 'cut': 960,
 'pieces': 961,
 'pumpkin': 962,
 'true': 963,
 'ancient': 964,
 'balloons': 965,
 'dizzy': 966,
 'lawyer': 967,
 'eager': 968,
 'extra': 969,
 'does': 970,
 'nosy': 971,
 'peace': 972,
 'clothes': 973,
 'using': 974,
 'bushes': 975,
 'case': 976,
 'rushed': 977,
 'dirt': 978,
 "i'll": 979,
 'funny': 980,
 'sitting': 981,
 'pile': 982,
 'stood': 983,
 'ask': 984,
 'colourful': 985,
 'sounds': 986,
 'wish': 987,
 'powder': 988,
 'poor': 989,
 'sadly': 990,
 'clumsy': 991,
 'letâ€™s': 992,
 'bugs': 993,
 'radio': 994,
 'arms': 995,
 'hurry': 996,
 'metal': 997,
 'chalk': 998,
 'knife': 999,
 'zipping': 1000,
 ...}

Create input sequences

In [ ]:
input_sequences = []
for line in text.split('.'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [ ]:
input_sequences

[[24, 17],
 [24, 17, 4],
 [24, 17, 4, 20],
 [24, 17, 4, 20, 27],
 [24, 17, 4, 20, 27, 84],
 [24, 17, 4, 20, 27, 84, 157],
 [24, 17, 4, 20, 27, 84, 157, 77],
 [24, 17, 4, 20, 27, 84, 157, 77, 4],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053, 11],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053, 11, 9],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053, 11, 9, 199],
 [7, 127],
 [7, 127, 8],
 [7, 127, 8, 5],
 [7, 127, 8, 5, 1054],
 [7, 127, 8, 5, 1054, 3],
 [7, 127, 8, 5, 1054, 3, 67],
 [7, 127, 8, 5, 1054, 3, 67, 19],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200, 8],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200, 8, 5],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200, 8, 5, 1177],
 [157, 39],
 [157, 39, 3],
 [157, 39, 3, 304],
 [157, 39, 3, 304, 1],
 [157, 39, 3, 304, 1, 1053],
 [157, 39, 3, 304, 1, 1053, 19],
 [157, 39, 3, 304, 1, 1053, 19, 9],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7, 58],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7, 58, 1997],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7, 58, 1997, 4],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7, 58, 1997, 4, 779],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7, 58, 1997, 4, 779, 28],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7, 58, 1997, 4, 779, 28, 9],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46, 10, 7, 58, 1997, 4, 779, 28, 9, 493],
 [157, 44],
 [157, 44, 3],
 [157, 44, 3, 9],
 [157, 44, 3, 9, 46],
 [157, 44, 3, 9, 46, 2],
 [157, 44, 3, 9, 46, 2, 12],
 [157, 44, 3, 9, 46, 2, 12, 46],
 [157, 44, 3, 9, 46, 2, 12, 46, 40],
 [157, 44, 3, 9, 46, 2, 12, 46, 40, 77],
 [157, 44, 3, 9, 46, 2, 12, 46, 40, 77, 99],
 [157, 44, 3, 9, 46, 2, 12, 46, 40, 77, 99, 1053],
 [66, 25],
 [66, 25, 304],
 [66, 25, 304, 8],
 [66, 25, 304, 8, 19],
 [66, 25, 304, 8, 19, 163],
 [66, 25, 304, 8, 19, 163, 2],
 [66, 25, 304, 8, 19, 163, 2, 1997],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9, 46],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9, 46, 42],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9, 46, 42, 2],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9, 46, 42, 2, 12],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9, 46, 42, 2, 12, 231],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9, 46, 42, 2, 12, 231, 157],
 [66, 25, 304, 8, 19, 163, 2, 1997, 164, 493, 9, 46, 42, 2, 12, 231, 157, 125],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66,
  304],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66,
  304,
  1],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66,
  304,
  1,
  1053],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66,
  304,
  1,
  1053,
  2],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66,
  304,
  1,
  1053,
  2,
  608],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66,
  304,
  1,
  1053,
  2,
  608,
  186],
 [66,
  25,
  304,
  8,
  19,
  163,
  2,
  1997,
  164,
  493,
  9,
  46,
  42,
  2,
  12,
  231,
  157,
  125,
  66,
  304,
  1,
  1053,
  2,
  608,
  186,
  493],
 [68, 13],
 [68, 13, 504],
 [68, 13, 504, 1],
 [68, 13, 504, 1, 1053],
 [68, 13, 504, 1, 1053, 2],
 [68, 13, 504, 1, 1053, 2, 2444],
 [68, 13, 504, 1, 1053, 2, 2444, 1],
 [68, 13, 504, 1, 1053, 2, 2444, 1, 779],
 [68, 13, 504, 1, 1053, 2, 2444, 1, 779, 28],
 [68, 13, 504, 1, 1053, 2, 2444, 1, 779, 28, 1526],
 [68, 13, 504, 1, 1053, 2, 2444, 1, 779, 28, 1526, 493],
 [8, 5],
 [8, 5, 112],
 [8, 5, 112, 1054],
 [8, 5, 112, 1054, 29],
 [8, 5, 112, 1054, 29, 81],
 [8, 5, 112, 1054, 29, 81, 200],
 [8, 5, 112, 1054, 29, 81, 200, 13],
 [8, 5, 112, 1054, 29, 81, 200, 13, 32],
 [8, 5, 112, 1054, 29, 81, 200, 13, 32, 1328],
 [8, 5, 112, 1054, 29, 81, 200, 13, 32, 1328, 2],
 [8, 5, 112, 1054, 29, 81, 200, 13, 32, 1328, 2, 724],
 [8, 5, 112, 1054, 29, 81, 200, 13, 32, 1328, 2, 724, 193],
 [8, 5, 112, 1054, 29, 81, 200, 13, 32, 1328, 2, 724, 193, 124],
 [118, 13],
 [118, 13, 443],
 [118, 13, 443, 157],
 [118, 13, 443, 157, 145],
 [118, 13, 443, 157, 145, 9],
 [118, 13, 443, 157, 145, 9, 46],
 [118, 13, 443, 157, 145, 9, 46, 29],
 [118, 13, 443, 157, 145, 9, 46, 29, 1328],
 [118, 13, 443, 157, 145, 9, 46, 29, 1328, 1],
 [118, 13, 443, 157, 145, 9, 46, 29, 1328, 1, 1053],
 [118, 13, 443, 157, 145, 9, 46, 29, 1328, 1, 1053, 2],
 [118, 13, 443, 157, 145, 9, 46, 29, 1328, 1, 1053, 2, 1998],
 [118, 13, 443, 157, 145, 9, 46, 29, 1328, 1, 1053, 2, 1998, 9],
 [118, 13, 443, 157, 145, 9, 46, 29, 1328, 1, 1053, 2, 1998, 9, 493],
 [13, 224],
 [13, 224, 69],
 [13, 224, 69, 31],
 [13, 224, 69, 31, 200],
 [13, 224, 69, 31, 200, 13],
 [13, 224, 69, 31, 200, 13, 18],
 [13, 224, 69, 31, 200, 13, 18, 504],
 [13, 224, 69, 31, 200, 13, 18, 504, 2],
 [13, 224, 69, 31, 200, 13, 18, 504, 2, 455],
 [13, 224, 69, 31, 200, 13, 18, 504, 2, 455, 68],
 [30, 34],
 [30, 34, 4],
 [30, 34, 4, 22],
 [30, 34, 4, 22, 21],
 [30, 34, 4, 22, 21, 5],
 [30, 34, 4, 22, 21, 5, 4],
 [30, 34, 4, 22, 21, 5, 4, 20],
 [30, 34, 4, 22, 21, 5, 4, 20, 249],
 [30, 34, 4, 22, 21, 5, 4, 20, 249, 84],
 [30, 34, 4, 22, 21, 5, 4, 20, 249, 84, 725],
 [725, 79],
 [725, 79, 3],
 [725, 79, 3, 57],
 [725, 79, 3, 57, 272],
 [725, 79, 3, 57, 272, 2],
 [725, 79, 3, 57, 272, 2, 67],
 [725, 79, 3, 57, 272, 2, 67, 11],
 [725, 79, 3, 57, 272, 2, 67, 11, 1],
 [725, 79, 3, 57, 272, 2, 67, 11, 1, 175],
 [725, 5],
 [725, 5, 4],
 [725, 5, 4, 1178],
 [725, 5, 4, 1178, 249],
 [725, 5, 4, 1178, 249, 200],
 [725, 5, 4, 1178, 249, 200, 6],
 [725, 5, 4, 1178, 249, 200, 6, 92],
 [725, 5, 4, 1178, 249, 200, 6, 92, 18],
 [725, 5, 4, 1178, 249, 200, 6, 92, 18, 228],
 [725, 5, 4, 1178, 249, 200, 6, 92, 18, 228, 1329],
 [228, 1329],
 [228, 1329, 90],
 [228, 1329, 90, 725],
 [228, 1329, 90, 725, 31],
 [228, 1329, 90, 725, 31, 2],
 [228, 1329, 90, 725, 31, 2, 329],
 [24, 17],
 [24, 17, 725],
 [24, 17, 725, 5],
 [24, 17, 725, 5, 1734],
 [24, 17, 725, 5, 1734, 11],
 [24, 17, 725, 5, 1734, 11, 1],
 [24, 17, 725, 5, 1734, 11, 1, 91],
 [24, 17, 725, 5, 1734, 11, 1, 91, 38],
 [24, 17, 725, 5, 1734, 11, 1, 91, 38, 6],
 [24, 17, 725, 5, 1734, 11, 1, 91, 38, 6, 33],
 [24, 17, 725, 5, 1734, 11, 1, 91, 38, 6, 33, 4],
 [24, 17, 725, 5, 1734, 11, 1, 91, 38, 6, 33, 4, 35],
 [24, 17, 725, 5, 1734, 11, 1, 91, 38, 6, 33, 4, 35, 139],
 [1, 139],
 [1, 139, 18],
 [1, 139, 18, 269],
 [1, 139, 18, 269, 337],
 [1, 139, 18, 269, 337, 16],
 [1, 139, 18, 269, 337, 16, 32],
 [1, 139, 18, 269, 337, 16, 32, 1735],
 [725, 194],
 [725, 194, 113],
 [725, 194, 113, 1],
 [725, 194, 113, 1, 337],
 [725, 194, 113, 1, 337, 862],
 [725, 194, 113, 1, 337, 862, 2],
 [725, 194, 113, 1, 337, 862, 2, 39],
 [725, 194, 113, 1, 337, 862, 2, 39, 3],
 [725, 194, 113, 1, 337, 862, 2, 39, 3, 67],
 [725, 194, 113, 1, 337, 862, 2, 39, 3, 67, 19],
 [725, 194, 113, 1, 337, 862, 2, 39, 3, 67, 19, 81],
 [725, 505],
 [725, 505, 609],
 [725, 505, 609, 1],
 [725, 505, 609, 1, 139],
 [725, 505, 609, 1, 139, 2],
 [725, 505, 609, 1, 139, 2, 220],
 [725, 505, 609, 1, 139, 2, 220, 1],
 [725, 505, 609, 1, 139, 2, 220, 1, 337],
 [725, 505, 609, 1, 139, 2, 220, 1, 337, 862],
 [725, 505, 609, 1, 139, 2, 220, 1, 337, 862, 28],
 [725, 505, 609, 1, 139, 2, 220, 1, 337, 862, 28, 43],
 [6, 182],
 [6, 182, 2],
 [6, 182, 2, 2445],
 [6, 182, 2, 2445, 15],
 [6, 182, 2, 2445, 15, 1999],
 [725, 235],
 [725, 235, 19],
 [725, 235, 19, 1],
 [725, 235, 19, 1, 1735],
 [725, 235, 19, 1, 1735, 337],
 [725, 235, 19, 1, 1735, 337, 36],
 [725, 235, 19, 1, 1735, 337, 36, 17],
 [38, 8],
 [38, 8, 5],
 [38, 8, 5, 22],
 [38, 8, 5, 22, 3],
 [38, 8, 5, 22, 3, 57],
 [38, 8, 5, 22, 3, 57, 74],
 [38, 8, 5, 22, 3, 57, 74, 725],
 [38, 8, 5, 22, 3, 57, 74, 725, 127],
 [38, 8, 5, 22, 3, 57, 74, 725, 127, 6],
 [38, 8, 5, 22, 3, 57, 74, 725, 127, 6, 456],
 [38, 8, 5, 22, 3, 57, 74, 725, 127, 6, 456, 132],
 [38, 8, 5, 22, 3, 57, 74, 725, 127, 6, 456, 132, 1329],
 [6, 44],
 [6, 44, 3],
 [6, 44, 3, 1],
 [6, 44, 3, 1, 1329],
 [6, 44, 3, 1, 1329, 250],
 [6, 44, 3, 1, 1329, 250, 2],
 [6, 44, 3, 1, 1329, 250, 2, 93],
 [6, 44, 3, 1, 1329, 250, 2, 93, 132],
 [6, 44, 3, 1, 1329, 250, 2, 93, 132, 1178],
 [6, 44, 3, 1, 1329, 250, 2, 93, 132, 1178, 1329],
 [147, 725],
 [147, 725, 5],
 [147, 725, 5, 259],
 [147, 725, 5, 259, 3],
 [147, 725, 5, 259, 3, 57],
 [147, 725, 5, 259, 3, 57, 272],
 [147, 725, 5, 259, 3, 57, 272, 2],
 [147, 725, 5, 259, 3, 57, 272, 2, 67],
 [147, 725, 5, 259, 3, 57, 272, 2, 67, 82],
 [147, 725, 5, 259, 3, 57, 272, 2, 67, 82, 1],
 [147, 725, 5, 259, 3, 57, 272, 2, 67, 82, 1, 243],
 [147, 725, 5, 259, 3, 57, 272, 2, 67, 82, 1, 243, 17],
 [2, 725],
 [2, 725, 176],
 [2, 725, 176, 346],
 [2, 725, 176, 346, 221],
 [2, 725, 176, 346, 221, 118],
 [24, 17],
 [24, 17, 4],
 [24, 17, 4, 20],
 [24, 17, 4, 20, 311],
 [24, 17, 4, 20, 311, 84],
 [24, 17, 4, 20, 311, 84, 1055],
 [24, 17, 4, 20, 311, 84, 1055, 5],
 [24, 17, 4, 20, 311, 84, 1055, 5, 863],
 [24, 17, 4, 20, 311, 84, 1055, 5, 863, 412],
 [24, 17, 4, 20, 311, 84, 1055, 5, 863, 412, 1],
 [24, 17, 4, 20, 311, 84, 1055, 5, 863, 412, 1, 726],
 [6, 33],
 [6, 33, 4],
 [6, 33, 4, 35],
 [6, 33, 4, 35, 650],
 [6, 33, 4, 35, 650, 2],
 [6, 33, 4, 35, 650, 2, 39],
 [6, 33, 4, 35, 650, 2, 39, 3],
 [6, 33, 4, 35, 650, 2, 39, 3, 47],
 [6, 33, 4, 35, 650, 2, 39, 3, 47, 49],
 [684, 40],
 [684, 40, 476],
 [684, 40, 476, 1055],
 [95, 25],
 [95, 25, 183],
 [95, 25, 183, 3],
 [95, 25, 183, 3, 67],
 [95, 25, 183, 3, 67, 60],
 [95, 25, 183, 3, 67, 60, 1],
 [95, 25, 183, 3, 67, 60, 1, 20],
 [95, 25, 183, 3, 67, 60, 1, 20, 311],
 [1, 650],
 [1, 650, 54],
 [1, 650, 54, 48],
 [1, 650, 54, 48, 1055],
 [1, 650, 54, 48, 1055, 2],
 [1, 650, 54, 48, 1055, 2, 12],
 [1, 650, 54, 48, 1055, 2, 12, 114],
 [1, 650, 54, 48, 1055, 2, 12, 114, 40],
 [1, 650, 54, 48, 1055, 2, 12, 114, 40, 187],
 [1, 650, 54, 48, 1055, 2, 12, 114, 40, 187, 183],
 [1, 650, 54, 48, 1055, 2, 12, 114, 40, 187, 183, 3],
 [1, 650, 54, 48, 1055, 2, 12, 114, 40, 187, 183, 3, 67],
 [40, 476],
 [40, 476, 359],
 [40, 476, 359, 2],
 [40, 476, 359, 2, 40],
 [40, 476, 359, 2, 40, 187],
 [40, 476, 359, 2, 40, 187, 195],
 [40, 476, 359, 2, 40, 187, 195, 1330],
 [1055, 69],
 [1055, 69, 120],
 [1055, 69, 120, 23],
 [1055, 69, 120, 23, 39],
 [1055, 69, 120, 23, 39, 3],
 [1055, 69, 120, 23, 39, 3, 70],
 [1055, 69, 120, 23, 39, 3, 70, 1],
 [1055, 69, 120, 23, 39, 3, 70, 1, 650],
 [1055, 69, 120, 23, 39, 3, 70, 1, 650, 195],
 [1055, 69, 120, 23, 39, 3, 70, 1, 650, 195, 207],
 [6, 1527],
 [6, 1527, 72],
 [6, 1527, 72, 2],
 [6, 1527, 72, 2, 115],
 [6, 1527, 72, 2, 115, 14],
 [6, 1527, 72, 2, 115, 14, 4],
 [6, 1527, 72, 2, 115, 14, 4, 780],
 [6, 360],
 [6, 360, 16],
 [6, 360, 16, 1],
 [6, 360, 16, 1, 175],
 [6, 360, 16, 1, 175, 58],
 [6, 360, 16, 1, 175, 58, 106],
 [6, 360, 16, 1, 175, 58, 106, 128],
 [6, 360, 16, 1, 175, 58, 106, 128, 316],
 [10, 1055],
 [10, 1055, 1527],
 [10, 1055, 1527, 3],
 [10, 1055, 1527, 3, 1],
 [10, 1055, 1527, 3, 1, 361],
 [10, 1055, 1527, 3, 1, 361, 14],
 [10, 1055, 1527, 3, 1, 361, 14, 1],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146, 3],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146, 3, 1],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146, 3, 1, 175],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146, 3, 1, 175, 444],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146, 3, 1, 175, 444, 175],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146, 3, 1, 175, 444, 175, 70],
 [10, 1055, 1527, 3, 1, 361, 14, 1, 142, 2, 146, 3, 1, 175, 444, 175, 70, 164],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2,
  1529],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2,
  1529,
  208],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2,
  1529,
  208,
  316],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2,
  1529,
  208,
  316,
  526],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2,
  1529,
  208,
  316,
  526,
  28],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2,
  1529,
  208,
  316,
  526,
  28,
  1],
 [10,
  1055,
  1527,
  3,
  1,
  361,
  14,
  1,
  142,
  2,
  146,
  3,
  1,
  175,
  444,
  175,
  70,
  164,
  109,
  110,
  195,
  1330,
  2,
  112,
  2000,
  1,
  175,
  148,
  2446,
  1528,
  2,
  1529,
  208,
  316,
  526,
  28,
  1,
  726],
 [1, 650],
 [1, 650, 61],
 [1, 650, 61, 3],
 [1, 650, 61, 3, 195],
 [1, 650, 61, 3, 195, 207],
 [1, 650, 61, 3, 195, 207, 2],
 [1, 650, 61, 3, 195, 207, 2, 112],
 [1, 650, 61, 3, 195, 207, 2, 112, 10],
 [1, 650, 61, 3, 195, 207, 2, 112, 10, 359],
 [6, 33],
 [6, 33, 1055],
 [6, 33, 1055, 2],
 [6, 33, 1055, 2, 12],
 [6, 33, 1055, 2, 12, 388],
 [6, 33, 1055, 2, 12, 388, 25],
 [6, 33, 1055, 2, 12, 388, 25, 20],
 [6, 33, 1055, 2, 12, 388, 25, 20, 311],
 [6, 33, 1055, 2, 12, 388, 25, 20, 311, 29],
 [6, 33, 1055, 2, 12, 388, 25, 20, 311, 29, 457],
 [6, 33, 1055, 2, 12, 388, 25, 20, 311, 29, 457, 163],
 [6, 33, 1055, 2, 12, 388, 25, 20, 311, 29, 457, 163, 195],
 [6, 33, 1055, 2, 12, 388, 25, 20, 311, 29, 457, 163, 195, 1330],
 [40, 187],
 [40, 187, 195],
 [40, 187, 195, 87],
 [40, 187, 195, 87, 40],
 [40, 187, 195, 87, 40, 154],
 [40, 187, 195, 87, 40, 154, 2000],
 [40, 187, 195, 87, 40, 154, 2000, 147],
 [149, 67],
 [149, 67, 68],
 [149, 67, 68, 2],
 [149, 67, 68, 2, 10],
 [149, 67, 68, 2, 10, 1055],
 [149, 67, 68, 2, 10, 1055, 2],
 [149, 67, 68, 2, 10, 1055, 2, 1],
 [149, 67, 68, 2, 10, 1055, 2, 1, 650],
 [149, 67, 68, 2, 10, 1055, 2, 1, 650, 235],
 [149, 67, 68, 2, 10, 1055, 2, 1, 650, 235, 2],
 [149, 67, 68, 2, 10, 1055, 2, 1, 650, 235, 2, 282],
 [149, 67, 68, 2, 10, 1055, 2, 1, 650, 235, 2, 282, 228],
 [149, 67, 68, 2, 10, 1055, 2, 1, 650, 235, 2, 282, 228, 49],
 [30, 34],
 [30, 34, 4],
 [30, 34, 4, 22],
 [30, 34, 4, 22, 11],
 [30, 34, 4, 22, 11, 4],
 [30, 34, 4, 22, 11, 4, 685],
 [30, 34, 4, 22, 11, 4, 685, 305],
 [30, 34, 4, 22, 11, 4, 685, 305, 14],
 [30, 34, 4, 22, 11, 4, 685, 305, 14, 389],
 [30, 34, 4, 22, 11, 4, 685, 305, 14, 389, 21],
 [30, 34, 4, 22, 11, 4, 685, 305, 14, 389, 21, 5],
 [30, 34, 4, 22, 11, 4, 685, 305, 14, 389, 21, 5, 4],
 [30, 34, 4, 22, 11, 4, 685, 305, 14, 389, 21, 5, 4, 20],
 [30, 34, 4, 22, 11, 4, 685, 305, 14, 389, 21, 5, 4, 20, 727],
 [30, 34, 4, 22, 11, 4, 685, 305, 14, 389, 21, 5, 4, 20, 727, 139],
 [1, 727],
 [1, 727, 139],
 [1, 727, 139, 5],
 [1, 727, 139, 5, 26],
 [1, 727, 139, 5, 26, 120],
 [1, 727, 139, 5, 26, 120, 200],
 [1, 727, 139, 5, 26, 120, 200, 8],
 [1, 727, 139, 5, 26, 120, 200, 8, 206],
 [1, 727, 139, 5, 26, 120, 200, 8, 206, 112],
 [1, 727, 139, 5, 26, 120, 200, 8, 206, 112, 76],
 [1, 727, 139, 5, 26, 120, 200, 8, 206, 112, 76, 477],
 [1, 727, 139, 5, 26, 120, 200, 8, 206, 112, 76, 477, 49],
 [36, 1],
 [36, 1, 124],
 [36, 1, 124, 389],
 [36, 1, 124, 389, 32],
 [36, 1, 124, 389, 32, 35],
 [36, 1, 124, 389, 32, 35, 2],
 [36, 1, 124, 389, 32, 35, 2, 329],
 [36, 1, 124, 389, 32, 35, 2, 329, 23],
 [36, 1, 124, 389, 32, 35, 2, 329, 23, 1],
 [36, 1, 124, 389, 32, 35, 2, 329, 23, 1, 727],
 [36, 1, 124, 389, 32, 35, 2, 329, 23, 1, 727, 139],
 [36, 1, 124, 389, 32, 35, 2, 329, 23, 1, 727, 139, 5],
 [36, 1, 124, 389, 32, 35, 2, 329, 23, 1, 727, 139, 5, 135],
 [36, 1, 124, 389, 32, 35, 2, 329, 23, 1, 727, 139, 5, 135, 2],
 [36, 1, 124, 389, 32, 35, 2, 329, 23, 1, 727, 139, 5, 135, 2, 1056],
 [1, 727],
 [1, 727, 139],
 [1, 727, 139, 5],
 [1, 727, 139, 5, 1057],
 [1, 727, 139, 5, 1057, 14],
 [1, 727, 139, 5, 1057, 14, 1],
 [1, 727, 139, 5, 1057, 14, 1, 35],
 [1, 727, 139, 5, 1057, 14, 1, 35, 389],
 [24, 17],
 [24, 17, 1],
 [24, 17, 1, 727],
 [24, 17, 1, 727, 139],
 [24, 17, 1, 727, 139, 69],
 [24, 17, 1, 727, 139, 69, 4],
 [24, 17, 1, 727, 139, 69, 4, 2447],
 [24, 17, 1, 727, 139, 69, 4, 2447, 11],
 [24, 17, 1, 727, 139, 69, 4, 2447, 11, 208],
 [24, 17, 1, 727, 139, 69, 4, 2447, 11, 208, 1736],
 [8, 5],
 [8, 5, 4],
 [8, 5, 4, 20],
 [8, 5, 4, 20, 2448],
 [8, 5, 4, 20, 2448, 399],
 [1, 399],
 [1, 399, 180],
 [1, 399, 180, 1],
 [1, 399, 180, 1, 727],
 [1, 399, 180, 1, 727, 139],
 [1, 399, 180, 1, 727, 139, 112],
 [1, 399, 180, 1, 727, 139, 112, 3],
 [1, 399, 180, 1, 727, 139, 112, 3, 47],
 [1, 399, 180, 1, 727, 139, 112, 3, 47, 120],
 [1, 399],
 [1, 399, 12],
 [1, 399, 12, 25],
 [1, 399, 12, 25, 209],
 [1, 399, 12, 25, 209, 83],
 [1, 399, 12, 25, 209, 83, 200],
 [1, 399, 12, 25, 209, 83, 200, 25],
 [1, 399, 12, 25, 209, 83, 200, 25, 76],

padding

In [ ]:
max_sequence_len = max([len(i) for i in input_sequences])
max_sequence_len

94

In [ ]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences.shape

(71052, 94)

Train test Split

In [ ]:
X,y = input_sequences[:,:-1],input_sequences[:,-1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  24],
       [  0,   0,   0, ...,   0,  24,  17],
       [  0,   0,   0, ...,  24,  17,   4],
       ...,
       [  0,   0,   0, ...,   6,  53,  98],
       [  0,   0,   0, ...,  53,  98,  47],
       [  0,   0,   0, ...,  98,  47, 575]], dtype=int32)

In [ ]:
y

array([ 17,   4,  20, ...,  47, 575,  82], dtype=int32)

In [ ]:
import tensorflow as tf

In [ ]:
y = tf.keras.utils.to_categorical(y,num_classes=total_words)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

Model Building

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,Input

Define the model

In [ ]:
model = Sequential()
model.add(Input(shape=(max_sequence_len,)))
model.add(Embedding(input_dim=total_words,output_dim=100))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))

compile the model

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 94, 100)        │       355,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 94, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 94, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3554)           │       358,954 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 965,354 (3.68 MB)

 Trainable params: 965,354 (3.68 MB)

 Non-trainable params: 0 (0.00 B)

Train the model

In [ ]:
history = model.fit(X_train,y_train,epochs=50,validation_data=(X_test,y_test),verbose=1)

Epoch 1/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 31s 16ms/step - accuracy: 0.3309 - loss: 3.0676 - val_accuracy: 0.2438 - val_loss: 5.5973
Epoch 2/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.3415 - loss: 2.9361 - val_accuracy: 0.2440 - val_loss: 5.6513
Epoch 3/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.3485 - loss: 2.8793 - val_accuracy: 0.2454 - val_loss: 5.7207
Epoch 4/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3552 - loss: 2.8447 - val_accuracy: 0.2400 - val_loss: 5.7817
Epoch 5/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.3604 - loss: 2.8086 - val_accuracy: 0.2402 - val_loss: 5.8372
Epoch 6/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3630 - loss: 2.7798 - val_accuracy: 0.2422 - val_loss: 5.8967
Epoch 7/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3684 - loss: 2.7428 - val_accuracy: 0.2418 - val_loss: 5.9230
Epoch 8/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.3738 - loss: 2.7125 - val_accuracy: 0.2426 - val_loss: 5.9621
Epoch 9/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3791 - loss: 2.6818 - val_accuracy: 0.2419 - val_loss: 6.0226
Epoch 10/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3839 - loss: 2.6563 - val_accuracy: 0.2378 - val_loss: 6.0528
Epoch 11/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 41s 16ms/step - accuracy: 0.3865 - loss: 2.6303 - val_accuracy: 0.2408 - val_loss: 6.0986
Epoch 12/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 42s 17ms/step - accuracy: 0.3892 - loss: 2.6062 - val_accuracy: 0.2388 - val_loss: 6.1390
Epoch 13/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3957 - loss: 2.5751 - val_accuracy: 0.2401 - val_loss: 6.1685
Epoch 14/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.4000 - loss: 2.5501 - val_accuracy: 0.2411 - val_loss: 6.2210
Epoch 15/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 42s 17ms/step - accuracy: 0.4055 - loss: 2.5234 - val_accuracy: 0.2385 - val_loss: 6.2468
Epoch 16/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 31s 17ms/step - accuracy: 0.4073 - loss: 2.5005 - val_accuracy: 0.2391 - val_loss: 6.3096
Epoch 17/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4116 - loss: 2.4756 - val_accuracy: 0.2385 - val_loss: 6.3760
Epoch 18/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4166 - loss: 2.4546 - val_accuracy: 0.2389 - val_loss: 6.3976
Epoch 19/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4208 - loss: 2.4313 - val_accuracy: 0.2374 - val_loss: 6.4258
Epoch 20/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.4252 - loss: 2.4069 - val_accuracy: 0.2366 - val_loss: 6.4508
Epoch 21/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.4273 - loss: 2.3899 - val_accuracy: 0.2355 - val_loss: 6.5067
Epoch 22/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4331 - loss: 2.3662 - val_accuracy: 0.2336 - val_loss: 6.5413
Epoch 23/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4349 - loss: 2.3485 - val_accuracy: 0.2377 - val_loss: 6.5734
Epoch 24/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4410 - loss: 2.3248 - val_accuracy: 0.2357 - val_loss: 6.6197
Epoch 25/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4436 - loss: 2.3051 - val_accuracy: 0.2347 - val_loss: 6.6568
Epoch 26/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 31s 18ms/step - accuracy: 0.4459 - loss: 2.2866 - val_accuracy: 0.2340 - val_loss: 6.6965
Epoch 27/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4516 - loss: 2.2665 - val_accuracy: 0.2315 - val_loss: 6.7380
Epoch 28/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 17ms/step - accuracy: 0.4536 - loss: 2.2488 - val_accuracy: 0.2329 - val_loss: 6.7653
Epoch 29/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 17ms/step - accuracy: 0.4587 - loss: 2.2318 - val_accuracy: 0.2344 - val_loss: 6.8079
Epoch 30/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4586 - loss: 2.2161 - val_accuracy: 0.2336 - val_loss: 6.8482
Epoch 31/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 41s 16ms/step - accuracy: 0.4635 - loss: 2.1929 - val_accuracy: 0.2349 - val_loss: 6.8875
Epoch 32/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.4657 - loss: 2.1778 - val_accuracy: 0.2339 - val_loss: 6.9181
Epoch 33/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 40s 16ms/step - accuracy: 0.4671 - loss: 2.1670 - val_accuracy: 0.2342 - val_loss: 6.9649
Epoch 34/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4731 - loss: 2.1441 - val_accuracy: 0.2337 - val_loss: 6.9843
Epoch 35/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.4757 - loss: 2.1284 - val_accuracy: 0.2337 - val_loss: 7.0274
Epoch 36/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.4788 - loss: 2.1218 - val_accuracy: 0.2293 - val_loss: 7.0582
Epoch 37/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4788 - loss: 2.1112 - val_accuracy: 0.2333 - val_loss: 7.1009
Epoch 38/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4838 - loss: 2.0911 - val_accuracy: 0.2300 - val_loss: 7.1235
Epoch 39/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 31s 17ms/step - accuracy: 0.4878 - loss: 2.0733 - val_accuracy: 0.2326 - val_loss: 7.1768
Epoch 40/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4914 - loss: 2.0606 - val_accuracy: 0.2283 - val_loss: 7.2253
Epoch 41/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4916 - loss: 2.0520 - val_accuracy: 0.2280 - val_loss: 7.2427
Epoch 42/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4945 - loss: 2.0334 - val_accuracy: 0.2279 - val_loss: 7.2562
Epoch 43/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.4960 - loss: 2.0225 - val_accuracy: 0.2294 - val_loss: 7.2652
Epoch 44/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.4994 - loss: 2.0086 - val_accuracy: 0.2260 - val_loss: 7.3442
Epoch 45/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 41s 17ms/step - accuracy: 0.5027 - loss: 1.9941 - val_accuracy: 0.2263 - val_loss: 7.3780
Epoch 46/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.5045 - loss: 1.9809 - val_accuracy: 0.2322 - val_loss: 7.4153
Epoch 47/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.5067 - loss: 1.9731 - val_accuracy: 0.2256 - val_loss: 7.4077
Epoch 48/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.5105 - loss: 1.9570 - val_accuracy: 0.2264 - val_loss: 7.4567
Epoch 49/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.5126 - loss: 1.9407 - val_accuracy: 0.2275 - val_loss: 7.4771
Epoch 50/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 17ms/step - accuracy: 0.5143 - loss: 1.9342 - val_accuracy: 0.2261 - val_loss: 7.5200

In [ ]:
def predict_next_word(model,tokenizer,text,max_sequence_len):
  token_list = tokenizer.texts_to_sequences([text])[0]
  if len(token_list) >= max_sequence_len:
    token_list = token_list[-(max_sequence_len):]
  token_list = pad_sequences([token_list], maxlen=max_sequence_len,padding='pre')
  predicted = model.predict(token_list,verbose=0)
  predicted_word_index = np.argmax(predicted,axis=1)
  for word, index in tokenizer.word_index.items():
    if index == predicted_word_index:
      return word
  return None

In [ ]:
input_text = "Who is enough for her mum who are you going to touch"
print(f"Input text : {input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next word : {next_word}")

Input text : Who is enough for her mum who are you going to touch
Next word : the

Save the model

In [ ]:
model.save('next_word_predictor_lstm.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Save tokenizer

In [ ]:
import pickle
with open('tokenizer.pickle','wb') as handle:
  pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)